- name: mettre le DNS sur le bon adaptateur ethernet
  ansible.windows.win_dns_client:
    adapter_names: 'Ethernet*'
    dns_servers: "{{ servers }}"

- name: Join the Windows host to the Active Directory domain and reboot
  microsoft.ad.membership:
    dns_domain_name: "{{ domain_name }}" 
    domain_admin_user: "{{ admin_user }}"
    domain_admin_password: "{{ admin_password }}"
    state: domain
    reboot: true 