- name: Ensure a server is a domain controller
  microsoft.ad.domain_controller:
    dns_domain_name: "{{ domain_name }}" 
    domain_admin_user: "{{ admin_user }}"
    domain_admin_password: "{{ admin_password }}"
    safe_mode_password: "{{ admin_password }}"
    state: domain_controller
    install_dns: true
    reboot: true
    