ad_domain_name: "pipotam.lab"
domain_admin_user: "administrator@pipotam.lab"
domain_admin_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      39616639653437396132623636313733303261643330353966643061366632393634343362633361
      3961393262626638613839656337363962643264353030330a643666613732373535373130613766
      39623537393438323234633030376461633837353065633531383633316564373862303038373863
      3935633364656262650a643738656133343765303963663663356334393766396139333034616232
      3732