ansible_user: ansible
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65313765666665303532613934356333396131396437386531613037396436313636376466383662
          3233363162313735393535316336393361623233616466350a633333373230663138396237393830
          36303236343065636364666131383731626333303230616633326630373932366538303065623334
          3664323161643863660a356336616430386632636433623632333038303961633464383133376335
          6466
